README.md

fixed a few things in main readme file too :3

---

iOS/Views/Settings/About/AboutViewController.swift

fix: iPadOS share button crash

---

Shared/Localizations/tr.lproj/Localizable.strings
feather.xcodeproj/project.pbxproj

This pull request includes the addition of Turkish localization to the project. The main changes involve updating the localization strings and the project configuration to include the new language.
Localization updates:
* [`Shared/Localizations/tr.lproj/Localizable.strings`](diffhunk://#diff-7fecd58c3ce25efd9b47b2ee005588eff27c36a5112ea0e0ec9db903e7439022R1-R326): Added Turkish translations for various UI elements, error messages, success messages, onboarding text, tab labels, transfer preview texts, view controller titles, and settings.
Project configuration updates:
* [`feather.xcodeproj/project.pbxproj`](diffhunk://#diff-04ee1a66c13dff709e9d4e6183446db573dffe9fc0960bfd1fd1aa905cf9afd8R242): Added references to the new Turkish localization file and updated the project configuration to …

feat: Add Turkish (tr) localization.

---

Shared/Localizations/ru.lproj/Localizable.strings

chore: russian localization update :3

---

Shared/Localizations/de.lproj/Localizable.strings

Replaced untranslated strings
Fixed confusing plural and non-plural strings

chore: german Localization Update

---

Shared/Data/CoreData/CoreDataManager+DownloadedApps.swift
Shared/Data/CoreData/CoreDataManager+SignedApps.swift
Shared/Data/Feather.xcdatamodeld/Feather.xcdatamodel/contents
Shared/Signing/AppSigner.swift
feather.xcodeproj/project.pbxproj
iOS/Delegates/AppDelegate.swift
iOS/Info.plist
iOS/Operations/SourceRefreshOperation.swift
iOS/Views/Apps/AppsTableViewCell.swift
iOS/Views/Apps/LibraryViewController.swift
iOS/Views/Signing/SigningViewController/SigningsViewController.swift

this aims to close #166 by implementing update checking, prompting, notifying and performing the install flow
this is probably extremely messy, I apologise, frankly the codebase was way bigger than I expected and I've just kinda been waddling through an ocean blindfolded

feat: app updates

---

README.md

Fix grammar mistake in README.md

---

Shared/Server/Server+TLS.swift

It works for me using both Wifi and Cellular

Fix Cellular online install

---

Shared/Magic/AppSigner.swift
Shared/Management/AppDownload.swift
Shared/Server/Server+TLS.swift

Here is an example: https://github.com/khcrysalis/Feather/issues/280

Fix blank app icon (some apps modified)

---

AltSourceKit/Sources/AltSourceKit/Models/ASRepository.swift
Feather.xcodeproj/project.pbxproj
Feather/Resources/Localizable.xcstrings

Added Turkish translation for Feather v2.

Added Turkish translation.

---

Feather.xcodeproj/project.pbxproj
Feather/Resources/Localizable.xcstrings

This pull request adds Indonesian (id-ID) language support to the Feather application. This change enables users to use the application in Indonesian language.
- Added Indonesian language localization file (`id-ID`)
- Updated `project.pbxproj` to accommodate the new language
- Added translations for all existing strings in the application
- All strings have been translated considering their context of use in the application
- Translations follow recommended iOS localization guidelines

feat: add Indonesian language support

---

CONTRIBUTING.md

Added point for contributing to the wiki.

chore: Update contribution guide to have a wiki section

---

Feather/Resources/Localizable.xcstrings

I noticed that this is the second time you've used `\\n `in the Localizable.xcstrings file.

lang(vi): update strings

---

Feather/Resources/Localizable.xcstrings

Adding translations for German

---

Feather/Backend/Storage/Storage+Certificate.swift
Feather/Utilities/FR.swift

Allows the user to pick what cert to export

---

Feather/Resources/Localizable.xcstrings

Hello, i live in Italy and i localized the whole app in italian. It would be cool to add this language in future updates! :)

Add Italian localization

---

Feather/Extensions/UIUserInterfaceStyle+cases.swift
Feather/Resources/Localizable.xcstrings
Feather/Views/Settings/Certificates/CertificatesCellView.swift
Feather/Views/Settings/Certificates/Info/CertificatesInfoView.swift
Feather/Views/Settings/Signing Options/ConfigurationView.swift

- Add missing Polish localizable
- Fixed some Polish localizable to make them more understandable
- Make footer and add description under Identifers
- PPQCheck
- Revoked
- App Icon
- Add localized
_I know it's labeled "do not translate", but I checked several apps on my phone and they all have this translation option :)_

Added missing and corrected Polish localizable + Few new localizable strings

---

AltSourceKit/Sources/AltSourceKit/Models/ASRepository.swift
Feather/Backend/Storage/Storage+Certificate.swift
Feather/Resources/Localizable.xcstrings
Feather/Views/Settings/Certificates/CertificatesView.swift
Feather/Views/Sources/Apps/Detail/ScreenshotPreviewView.swift
Feather/Views/Sources/Apps/Detail/SourceAppsDetailView.swift

Screenshots on tap will show a preview

Feather(Views): Screenshots on tap will show a preview

---

Feather/Resources/Localizable.xcstrings

lang(tr): Updated translations.

---

Feather.xcodeproj/project.pbxproj
Feather/Resources/Localizable.xcstrings

Add localisation for Simplified Chinese.
By the way, I'm unsure about the "Show Sheet when Exporting" in the Archive & Compression setting and I kept the "Sheet" unchanged. Would anyone be able to give me a brief explanation about what it does so I can make it more precise?

lang(zh-hans): adding simplified Chinese localisation
